export const API_ENDPOINTS = {
  assiduite: '/api/assiduite/',
  authLogin: '/api/auth/login/',
  authRefresh: '/api/auth/token/refresh/',
  communication: '/api/communication/',
  conges: '/api/conges/',
  demandes: '/api/demandes/',
  demandeurs: '/api/demandeurs/',
  depenses: '/api/depenses/',
  emploiDuTemps: '/api/emploi-du-temps/',
  etudiants: '/api/etudiants/',
  etudiantsPortal: '/api/etudiants/portal/',
  formateurs: '/api/formateurs/',
  formations: '/api/formations/',
  niveaux: '/api/niveaux/',
  inscriptions: '/api/inscriptions/',
  inventaires: '/api/inventaires/',
  modules: '/api/modules/',
  notes: '/api/notes/',
  paies: '/api/paie/paies/',
  paieForecast: '/api/paie/forecast/',
  paieContentTypes: '/api/paie/content-types/',
  paiements: '/api/paiements/',
  paiementsAggregated: '/api/paiements/aggregated/',
  paiementsDashboard: '/api/paiements/dashboard/',
  paiementsConfigurations: '/api/paiements/configurations/',
  paiementsPlans: '/api/paiements/plans/',
  paiementsAlerts: '/api/paiements/alerts/',
  classSchedules: '/api/paiements/class-schedules/',
  studentSchedule: '/api/paiements/student-schedule/',
  personnels: '/api/personnels/',
  revenus: '/api/revenus/',
  users: '/api/auth/',
  userRoles: '/api/auth/roles/',
  preinscriptions: '/api/v2/pre-inscriptions/',
  frais: '/api/v2/frais/',
  paiementsV2: '/api/v2/paiements/',
  notesV2: '/api/v2/notes/',
  domaines: '/api/v2/domaines/',
  facultes: '/api/v2/facultes/',
  filieresV2: '/api/v2/filieres/',
  specialites: '/api/v2/specialites/',
  classes: '/api/v2/classes/',
  cycles: '/api/v2/cycles/',
  cyclesGlobaux: '/api/v2/cycles-globaux/',
  levelsV2: '/api/v2/levels/',
  coursesV2: '/api/v2/courses/',
  anneesAcademiques: '/api/v2/annees-academiques/',
  semestres: '/api/v2/semestres/',
  epreuves: '/api/v2/epreuves/',
  inscriptionsV2: '/api/v2/inscriptions/',
  evaluations: '/api/v2/evaluations/',
  affectations: '/api/v2/affectations/',
  emploisDuTempsV2: '/api/v2/emplois-du-temps/',
  parametresGlobaux: '/api/v2/parametres-globaux/',
  configurationEtablissement: '/api/v2/configuration-etablissement/',
  notesV2ExportTemplate: '/api/v2/notes/export-template/',
  notesV2ExportTemplateNiveau: '/api/v2/notes/export-template-niveau/',
  notesV2Import: '/api/v2/notes/import-notes/',
  notesV2ImportNiveau: '/api/v2/notes/import-notes-niveau/',
  formateurPortal: '/api/formateurs/portal/',
  formateurCoursDocuments: '/api/formateurs/cours-documents/',
  formateurCoursEtudiants: '/api/formateurs/cours-etudiants/',
  salles: '/api/salles/',
  // Inventaire v2
  articles: '/api/inventaires/articles/',
  exemplaires: '/api/inventaires/exemplaires/',
  mouvements: '/api/inventaires/mouvements/',
  inventaireStats: '/api/inventaires/stats/',
  // Demandes v2
  demandesStats: '/api/demandes/stats/',
  // Paie complète
  paiesPrimes: '/api/paie/primes/',
  paiesRetenues: '/api/paie/retenues/',
  paiesAvances: '/api/paie/avances/',
  paiesBulletins: '/api/paie/bulletins/',
  paiesCampagnes: '/api/paie/campagnes/',
  paiesGenererCampagne: '/api/paie/campagnes/generer/',
  paiesStatistiques: '/api/paie/statistiques/',
};

export function idPath(basePath, id) {
  return `${basePath}${id}/`;
}
